In [1]:
N = 6  # number of sites
V = 1.0  # coupling strength

In [2]:
from itertools import combinations
import numpy as np

def generate_basis(N, N_particles):
    basis = []
    sites = list(range(N))
    for comb in combinations(sites, N_particles):
        state = np.zeros(N, dtype=int)
        state[list(comb)] = 1
        basis.append(state)
    return basis

In [3]:
print(np.array(generate_basis(4, 2)))

[[1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]]


In [5]:
def build_hamiltonian(basis, V):
    size = len(basis)
    H = np.zeros((size, size), dtype=float)

    for idx, state in enumerate(basis):
        energy = 0.0
        for i in range(len(state) - 1):
            energy += V * state[i] * state[i+1]
        H[idx, idx] = energy

    return H

In [9]:
import scipy as sp
basis = generate_basis(500, 250)
H = build_hamiltonian(basis, V)


print(np.array(H))
print(sp.linalg.ishermitian(H))

KeyboardInterrupt: 